name: Docker ARM Build
on: [workflow_dispatch] # handmatige trigger

jobs:
  build-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --platform=linux/arm -t pi-builder .

      - name: Run Docker container to compile main
        run: docker run --rm --platform=linux/arm -v ${{ github.workspace }}/pigpio-master:/work/pigpio -v ${{ github.workspace }}/project:/work/project pi-builder
